### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by masafumimori** [Chainlit/docs#10]
Path: /examples/mrkl

The link at the top of the page to LangChain MRKL is not working.
`Example inspired from the [LangChain doc](https://python.langchain.com/en/latest/modules/agents/agents/examples/mrkl_chat.html)`

Maybe they moved to this page?
https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent

I can fix it for you if you would like.

**Comment by willydouhard** [comment]
good catch, you can fork the repo and make a PR 👍

**Comment by constantinidan** [comment]
Fixed it in latest commit
