### ISSUE TITLE
Loader not working with cl.sleep

### ISSUE THREAD

**Issue by httplups** [Chainlit/docs#100]
I was following the tutorial to display the loader (running) while awaiting for the response, but it is not working. 
I just copy the code from the documentation.

```
import chainlit as cl

@cl.on_chat_start
async def main():
    msg = cl.Message(content="Hello!")
    await msg.send()

    await cl.sleep(2)

    msg.content = "Hello again!"
    await msg.update()
```

It appears Hello, after a few seconds appears Hello Again, but the loader is not shown

**Comment by willydouhard** [comment]
It only works while the content is empty.

Replace `msg = cl.Message(content="Hello!")` with `msg = cl.Message(content="")`.

**Comment by ModEnter** [comment]
This issue has been answered
