### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'to_openai'

### ISSUE THREAD

**Issue by DonaghBr** [Chainlit/docs#105]
Path: /examples/openai-sql

When I ran the app I got this AttributeError: 'dict' object has no attribute 'to_openai'?

**Comment by hfinda** [comment]
Updated code 

    stream = await client.chat.completions.create(
        messages=generation.messages, stream=True, **settings
    )

it will work... all the best

**Comment by DonaghBr** [comment]
That worked - thanks so much

**Comment by ModEnter** [comment]
I'm closing this issue
