### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Shahwar-Alam-Naqvi** [Chainlit/docs#117]
Path: /api-reference/lifecycle-hooks/on-message
@cl.on_chat_start works fine but , @cl.on_message is not working although I have followed the documentation.

**Comment by ModEnter** [comment]
Hello, it is expected behaviour that the documentation's `cl.on_message` callback does nothing :
```python
import chainlit as cl

@cl.on_message
def main(message: cl.Message):
  content = message.content
  # do something
```

as you can see, you have to implement your own behaviour after catching the message. Refer to Chainlit/cookbook for comprehensive examples
