### ISSUE TITLE
Issue on integrating chat resume.

### ISSUE THREAD

**Issue by Rajatkhanna801** [Chainlit/docs#120]
Hi All,

I am sqlite as data persistence layer and Microsoft Authentication. I want to fix chat resume feature for my application. Can anyone help me with that.

Here is my code.

@cl.on_chat_resume
async def on_chat_resume(thread: cl_data.ThreadDict):
    memory = []
    root_messages = [m for m in thread["steps"] if m["parentId"] == 'None']
    for message in root_messages:
        if message["type"] == "user_message":
            memory.append({"role": "user", "content": message["output"]})
        else:
            memory.append({"role": "assistant", "content": message["output"]})
    cl.user_session.set("memory", memory)
    await cl.Message(memory).send()`
![Uploading Screenshot from 2024-04-02 17-51-59.png…]()
`

**Comment by dahifi** [comment]
Use triple ticks /`/`/` for multiline code: 
I assume you mean this?: 
```
@cl.on_chat_resume
async def on_chat_resume(thread: cl_data.ThreadDict):
    memory = []
    root_messages = [m for m in thread["steps"] if m["parentId"] == 'None']
    for message in root_messages:
        if message["type"] == "user_message":
            memory.append({"role": "user", "content": message["output"]})
        else:
            memory.append({"role": "assistant", "content": message["output"]})
    cl.user_session.set("memory", memory)
    await cl.Message(memory).send()
```
I suggest you set debugging in your app.py and step through it. 

Just from the looks of it, you're trying to pass a list of messages to cl.Message's init, you'd need to interate through them individually and send

**Comment by Rajatkhanna801** [comment]
@dahifi 

Can you send me some examples how I can send the Message in iterations?

**Comment by dahifi** [comment]
Was just looking at the example i[n the cookbook](https://github.com/Chainlit/cookbook/blob/ddcdcdc91ec169a8d8c52a66826dd8daa17d002c/resume-chat/app.py#L48): 

Setting cl.user_session memory like you're doing should be sufficient to bring the messages back into the UX, you only want to call Message.send if you want to provide an additional message back to the user.

**Comment by Rajatkhanna801** [comment]
Hi @dahifi 
I have set the user_session memory but still is not showing user previous messages. Can you please help me with that.
I have also tried the example given but that is also not working.

**Comment by Rajatkhanna801** [comment]
My complete code file

```
from typing import Optional, Dict
import chainlit.data as cl_data
from datalayer import SQLiteDataLayer
from chainlit.types import ThreadDict
from openai import AsyncClient
import chainlit as cl
import asyncio
import os



# user Authentication
@cl.password_auth_callback
def auth_callback(username: str, password: str) -> Optional[cl.User]:
    if (username, password) == ("admin", "admin"):
        return cl.User(identifier="admin")
    else:
        return None


# Authentication with Microsoft
@cl.oauth_callback
def oauth_callback(provider_id: str, token: str,
    raw_user_data: Dict[str, str],
    default_user: cl.User,) -> Optional[cl.User]:
    return default_user


# setting up custom data layer.
cl_data._data_layer = SQLiteDataLayer("user_database/chainlit.db")


# Initilizing AsyncClient and integrating openai API.
openai_client = AsyncClient(api_key=os.environ.get("OPENAI_API_KEY"))
model_name = "gpt-3.5-turbo"
settings = {
    "temperature": 0.3,
    "max_tokens": 500,
    "top_p": 1,
    "frequency_penalty": 0,
    "presence_penalty": 0,
}


@cl.on_chat_start
async def start_chat():
    cl.user_session.set(
        "message_history", []
    )
    await cl.Avatar(
        name="Gilfoyle",
        url="https://static.wikia.nocookie.net/silicon-valley/images/2/20/Bertram_Gilfoyle.jpg",
    ).send()
    await cl.Avatar(
        name="Dinesh",
        url="https://static.wikia.nocookie.net/silicon-valley/images/e/e3/Dinesh_Chugtai.jpg",
    ).send()


# helper functiom to call openai API.
async def answer_as(name):
    message_history = cl.user_session.get("message_history")
    msg = cl.Message(author=name, content="")
    stream = await openai_client.chat.completions.create(
        model=model_name,
        messages=message_history,
        stream=True,
        **settings,
    )
    async for part in stream:
        if token := part.choices[0].delta.content or "":
            await msg.stream_token(token)
    await msg.send()


@cl.on_message
async def main(message: cl.Message):
    message_history = cl.user_session.get("message_history")
    message_history.append({"role": "user", "content": message.content})
    await asyncio.gather(answer_as("Gilfoyle"))


@cl.on_chat_resume
async def on_chat_resume(thread: ThreadDict):
    message_history = []
    root_messages = [m for m in thread["steps"] if m["parentId"] == 'None']
    for message in root_messages:
        if message["type"] == "user_message":
            message_history.append({"role": "user", "content": message["output"]})
        else:
            message_history.append({"role": "Gilfoyle", "content": message["output"]})
    cl.user_session.set("memory", message_history)
    
 ```

**Comment by Rajatkhanna801** [comment]
In resume chat I am seting the user session memory but still does not show the previous message on browser.

**Comment by geekharsh** [comment]
I am also facing same proble message history not updating on UI
@Rajatkhanna801  can you provide me the implementation of SQLiteDataLayer

You can take a look of my tries - https://github.com/geekharsh/python/blob/main/chainlit_ui.py

**Comment by Rajatkhanna801** [comment]
@geekharsh 
yes sure. I have already fix the issue.

**Comment by Rajatkhanna801** [comment]
Provide me permission to acces this Repo.

**Comment by Rajatkhanna801** [comment]
@geekharsh 
Access this repo https://github.com/Rajatkhanna801/chainlit_sqlite. Let me know if you need any help.

**Comment by geekharsh** [comment]
Thanks a lot,
this will work, will let you know

**Comment by geekharsh** [comment]
@Rajatkhanna801  Good work bro, But i have a question, I am looking at the way in which, the user click on new chat, the current chat will go in chat history will reflect on chat history box, Right now it is appearing after manual page refresh.

**Comment by Rajatkhanna801** [comment]
Yes right @geekharsh 
I have also done that but that need change in frontend side.

**Comment by zaltesagar** [comment]
@Rajatkhanna801 Can you please give me access to repo https://github.com/Rajatkhanna801/chainlit_sqlite. I am facing same issue

**Comment by Rajatkhanna801** [comment]
@zaltesagar 
Access granted .....

**Comment by zaltesagar** [comment]
@Rajatkhanna801 I have created tables like users,threads,feedback,steps,elements in postgres and created datalayer to store data into it. When I run chainlit application the feedbacks are stored in table but also want to show chat history on UI but not able to show it on UI. Is there any way to show it?

**Comment by ModEnter** [comment]
Hello, the issue section is not meant to be used as a messaging application. Please use the Chainlit discord server to discuss technical issues.

**Comment by adhil-tinvio** [comment]
@Rajatkhanna801  can you please give me access as well.
facing the same .needed your help

**Comment by luckfu** [comment]
@Rajatkhanna801 Can you please give me access to repo https://github.com/Rajatkhanna801/chainlit_sqlite

**Comment by Rajatkhanna801** [comment]
@luckfu 
I have added the access.

**Comment by gajanandC** [comment]
Hi @Rajatkhanna801 could you please give the access to the repo https://github.com/Rajatkhanna801/chainlit_sqlite to me as well

**Comment by Rajatkhanna801** [comment]
Hey @luckfu @gajanandC 
I have made this repo public now.
