### ISSUE TITLE
Missing dependencies in docs

### ISSUE THREAD

**Issue by hosmanadam** [Chainlit/docs#134]
Path: /advanced-features/prompt-playground/setup

The code on this page does not work until an LLM provider is configured, which is only mentioned 2 pages later [here](https://docs.chainlit.io/advanced-features/prompt-playground/llm-providers). I suggest either mentioning the dependency or changing the order of pages.

**Comment by ModEnter** [comment]
Hello, the prompt playground feature has been removed from chainlit, I'm closing the issue
