### ISSUE TITLE
Issue on docs: @cl.set_starters is not working

### ISSUE THREAD

**Issue by MousaMohammad** [Chainlit/docs#152]
Path: /concepts/starters

I created a basic chainlit project and once I added this code from the docs

import chainlit as cl
@cl.set_starters
async def set_starters():
    return [
        cl.Starter(
            label="Morning routine ideation",
            message="Can you help me create a personalized morning routine that would help increase my productivity throughout the day? Start by asking me about my current habits and what activities energize me in the morning.",
            icon="/public/idea.svg",
            ),
        cl.Starter(
            label="Explain superconductors",
            message="Explain superconductors like I'm five years old.",
            icon="/public/learn.svg",
            ),
        ]
 
I got this error: .../lib/python3.11/site-packages/chainlit/utils.py", line 64, in __getattr__
    module_path = registry[name]
                  ~~~~~~~~^^^^^^
KeyError: 'set_starters'

**Comment by ModEnter** [comment]
This issue has been fixed. I'm closing this issue.

**Comment by reemabdelrazek30** [comment]
We are having the same issue today with python3.10.15!
