### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by inrsta** [Chainlit/docs#155]
Path: /customisation/avatars

The docs say if the author is named My Assistant the file should be named my-assistant.png. What is the rule here exactly, all underscore letters seperated by a dash? What if the assistant was called MyAssistant, what should the name of the file be in that case?

**Comment by LucasMagnum** [comment]
https://github.com/Chainlit/docs/pull/159 is supposed to fix the docs, if you don't have spaces the file should be called `myassistant`. You can check the code here: https://github.com/Chainlit/chainlit/blob/add72385a2b8013e60718b65e2e82eb385a51773/backend/chainlit/server.py#L914
