### ISSUE TITLE
Regarding Feedback feature

### ISSUE THREAD

**Issue by vibhav-bidgely** [Chainlit/docs#157]
I'm currently developing an app using Chainlit and have enabled feedback options with the Literal API key. While I can view all threads, steps, and feedback on the Literal AI dashboard, I need to fetch the feedback comments directly from the UI to a chainlitapp.py file for additional purposes.

Are there any direct functions or methods within Chainlit that allow for fetching and storing these feedback comments locally? Any guidance or examples would be greatly appreciated.

**Comment by ModEnter** [comment]
Hello, this is out of the chainlit scope, so it is not planned, but you can catch the feedbacks yourself by modifying the PUT route in https://github.com/Chainlit/chainlit/blob/74636a990eb989068bfcb7a5b03122cc356cb10a/backend/chainlit/server.py#L682

Hope that helps, I'm closing the issue
