### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Dannyjelll** [Chainlit/docs#166]
Path: /data-persistence/overview

Why is there no explanation of the custom data layer here?
Shouldn't this be linked at least: https://docs.chainlit.io/data-persistence/custom ?

**Comment by ModEnter** [comment]
The page https://docs.chainlit.io/data-persistence/custom has been added to the data persitence overview's page.

**Comment by ModEnter** [comment]
This issue has been fixed
