### ISSUE TITLE
FastAPI integration returns "Could not reach the server"

### ISSUE THREAD

**Issue by ndamulelonemakh** [Chainlit/docs#172]
Path: /integrations/fastapi

This integration appears to be broken. The app returns an error "Could not reach server"

![image](https://github.com/user-attachments/assets/0ebccd94-4251-4cc5-bb94-e87b6eeb61cf)

I followed the exact same steps as outline in the docs. and I keep getting the error.

Chainlit version:  1.1.404
FastAPI version:   0.110.3
Uvicorn version: 0.25.0

**Comment by ModEnter** [comment]
Hello, this issue has been fixed in this PR : https://github.com/Chainlit/chainlit/pull/1337
Thank you for your feedback, I'm closing the issue
