### ISSUE TITLE
set_starters() not working. I used this functionality in my code. The starter questions get flashed for a micro-second then disappear. 

### ISSUE THREAD

**Issue by kumar781** [Chainlit/docs#180]
**set_starters() not working. I used this functionality in my code. The starter questions get flashed for a micro-second then disappear.

chainlit version: 1.1.304**

The code block looks like this:
@cl.set_starters
async def set_starters():
    return [
        cl.Starter(
            label="Morning routine ideation",
            message="Can you help me create a personalized morning routine that would help increase my productivity throughout the day? Start by asking me about my current habits and what activities energize me in the morning.",
        ),
        cl.Starter(
            label="Explain superconductors",
            message="Explain superconductors like I'm five years old.",
        ),
    ]

**Comment by ModEnter** [comment]
are you using chat profiles ? the chat profiles feature is not compatible with the starters feature

**Comment by kumar781** [comment]
I am not using chat profiles.

**Comment by kumar781** [comment]
@cl.set_starters
async def set_starters():
return [
cl.Starter(
label="Morning routine ideation",
message="Can you help me create a personalized morning routine that would help increase my productivity throughout the day? Start by asking me about my current habits and what activities energize me in the morning.",
),
cl.Starter(
label="Explain superconductors",
message="Explain superconductors like I'm five years old.",
),
]

@cl.on_chat_start
async def on_chat_start():

    await cl.Message(content="Hi, how can I help you?").send()
    llm code
    load_qa chain...
    cl.user_session.set("chain", chain)

@cl.on_message
async def on_message(message: cl.Message):
    chain = cl.user_session.get("chain")

    cb = cl.AsyncLangchainCallbackHandler()
    ......

**Comment by kumar781** [comment]
On the UI i tried inspecting element and used the following commands to stop it from getting disappeared:
document.querySelectorAll('div').forEach( function(element, index) { element.style.opacity = '1'; })
 
document.querySelectorAll('div').forEach( function(element, index) { element.style.visibility = null; })
 
 
 However, it gets superimposed on other copilot responses and it is not clickable either.

**Comment by ModEnter** [comment]
It is because you send a message on start : the starters screen is shown before messages.

```python
@cl.on_chat_start
async def on_chat_start():
    await cl.Message(content="Hi, how can I help you?").send()
 ```

**Comment by kumar781** [comment]
I see it works by removing the 'await cl.Message(content="Hi, how can I help you?").send()'. But i need this message at the top. Any other way i can still have this entry message and the starter questions as tiles?

**Comment by ModEnter** [comment]
No, the starters screen and the messages screen are not compatible, as the starters disappear after the first message is sent

**Comment by kumar781** [comment]
okay, I also want the starter questions to take in json attachments which are attached but not submitted till that point. Can this be achieved?

**Comment by ModEnter** [comment]
Sorry missclick, you can achieve this with an asynchronous function on start. Please use the Discord server for future question, as this page only refers to issues on the Chainlit documentation.

**Comment by kumar781** [comment]
i am unable to get access to the discord channel. Can you send me an invite or something?

**Comment by ModEnter** [comment]
The link is in footer of all the documentation pages, in the discord icon

**Comment by kumar781** [comment]
Tried that already, here's what i get:
![image](https://github.com/user-attachments/assets/aeac3ae1-c9ed-4c65-a347-44b07b2c0b19)

**Comment by ModEnter** [comment]
I don’t have a solution, it is an issue on your end since the link is working.
