### ISSUE TITLE
Error reloading module: No module named 'chainlit.input_widget'

### ISSUE THREAD

**Issue by piecesyoyo** [Chainlit/docs#25]
Path: /api-reference/chat-settings

**Comment by constantinidan** [comment]
can you upgrade the package? pip install --upgrade chainlit

**Comment by iceman3000** [comment]
Hey guys, the default pip install is doing version 0.5.2 - had to install using latest version (at time of writing) using pip install chainlit==0.6.1 (as shown in Github)

**Comment by constantinidan** [comment]
hey @iceman3000 
the default pip install chainlit should install the version 0.6.2 (at the time of writing)
can you try pip install --upgrade chainlit
