### ISSUE TITLE
not a valid model id

### ISSUE THREAD

**Issue by Conqueror712** [Chainlit/docs#32]
When I type something on the localhost board and send it, three messages are returned: 
> LLMChain: not a valid model id
> Chatbot: not a valid model id
> Error: not a valid model id

I have changed the environment variable : export GPT_MODEL="gpt-3.5-turbo"
Is it correct? Please help me.

**Comment by willydouhard** [comment]
Can you provide a minimal reproducible example of your code?

**Comment by Conqueror712** [comment]
> 

Just like this link, Step1 & Step2: https://docs.smith.langchain.com/tracing/use-cases/track-sentiment

**Comment by Conqueror712** [comment]
> Can you provide a minimal reproducible example of your code?

Just like this link, Step1 & Step2: https://docs.smith.langchain.com/tracing/use-cases/track-sentiment

**Comment by constantinidan** [comment]
@Conqueror712 could you provide a full code example of what you are running? thanks
