### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by xg35** [Chainlit/docs#38]
Path: /integrations/langflow

I don't think this example works.. i get this error:

2023-09-13 11:41:13 - load_flow_from_json() got an unexpected keyword argument 'flow'
Traceback (most recent call last):
  File "/Users/simonau/Documents/Lending/env/lib/python3.11/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simonau/Documents/Lending/main_tool_langflow.py", line 15, in start
    flow = await load_flow(schema=schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simonau/Documents/Lending/env/lib/python3.11/site-packages/chainlit/langflow/__init__.py", line 30, in load_flow
    flow = load_flow_from_json(flow=schema, tweaks=tweaks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_flow_from_json() got an unexpected keyword argument 'flow'
2023-09-13 11:41:13 - load_flow_from_json() got an unexpected keyword argument 'flow'

**Comment by willydouhard** [comment]
Nice catch, what version of langflow are you using? Can you try upgrading it? Or maybe they released a breaking change.

**Comment by willydouhard** [comment]
This seems pretty [outdated](https://pypi.org/project/langflow/#history), can you run `pip -U langflow` and try again?

**Comment by xg35** [comment]
yeah updated it to 0.4.16 and similar error:

TypeError: load_flow_from_json() got an unexpected keyword argument 'flow'
2023-09-13 16:32:38 - 'NoneType' object has no attribute 'agent'
Traceback (most recent call last):
  File "/Users/simonau/Documents/Lending/env/lib/python3.11/site-packages/chainlit/utils.py", line 40, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simonau/Documents/Lending/main_tool_langflow.py", line 29, in main
    flow.agent.llm_chain.llm.streaming = True
    ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'agent'

**Comment by willydouhard** [comment]
So this error is a bit different, the flow was successfully loaded but it no longer have an `agent` attribute. But at least this is reaching the code of your app file.

**Comment by xg35** [comment]
import json

from langchain.agents import AgentExecutor
from langflow import load_flow_from_json
from chainlit.langflow import load_flow
import chainlit as cl

#import os

#os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
#os.environ["SERPAPI_API_KEY"] = os.getenv("SERPAPI_API_KEY")

with open("./schema.json", "r") as f:
    schema = json.load(f)


@cl.on_chat_start
async def start():
    flow = await load_flow(schema=schema)
    cl.user_session.set("flow", flow)


@cl.on_message
async def main(message):
    # Load the flow from the user session
    flow = cl.user_session.get("flow")  # type: AgentExecutor

    # Enable streaming
    flow.agent.llm_chain.llm.streaming = True

    # Run the flow
    res = await cl.make_async(flow.run)(
        message, callbacks=[cl.LangchainCallbackHandler()]
    )

    # Send the response
    await cl.Message(content=res).send()

This is the exact code.

**Comment by willydouhard** [comment]
maybe update the main function like so:

```py
@cl.on_message
async def main(message):
# Load the flow from the user session
flow = cl.user_session.get("flow") # type: AgentExecutor

# Run the flow
res = await cl.make_async(flow)(
    message, callbacks=[cl.LangchainCallbackHandler()]
)

# Send the response
await cl.Message(content=res).send()
```

**Comment by xg35** [comment]
<img width="975" alt="image" src="https://github.com/Chainlit/docs/assets/129599379/39b8577f-2d1a-41ec-89a8-68225b62a396">

that indeed did the job. now looks like this

**Comment by xg35** [comment]
Any idea how i can get it parse it correctly?

**Comment by willydouhard** [comment]
What do you mean by "parsing"?
