### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by darylmoodys** [Chainlit/docs#42]
Path: /concepts/feedback

https://docs.chainlit.io/cloud/persistence/custom link on documentation page for custom data persistence is broken,

**Comment by willydouhard** [comment]
Should be fixed!

**Comment by darylmoodys** [comment]
Could I check, is it supposed to route me to the "Overview" page? When I clicked on https://docs.chainlit.io/cloud/persistence/custom I get redirected to https://docs.chainlit.io/overview instead.
