### ISSUE TITLE
Error In Importing AppUser For Authentication.

### ISSUE THREAD

**Issue by prashant2-4-4** [Chainlit/docs#44]
Path: /authentication/password

 from chainlit.types import AppUser
 ImportError: cannot import name 'AppUser' from 'chainlit.types' (/opt/conda/envs/wiki/lib/python3.8/site-packages/chainlit/types.py)

**Comment by prashant2-4-4** [comment]
chainlit                  0.5.2  

Chainlit version I am using.

**Comment by willydouhard** [comment]
AppUser is introduced in chainlit `0.7.0`.
