### ISSUE TITLE
I am unable to run chainlit on my system

### ISSUE THREAD

**Issue by bhushan-ss** [Chainlit/docs#48]
I am unable to run chainlit on my system.
When I run chainlit run app.py -w it says -  2023-09-27 19:29:08 - Your app is available at http://localhost:8000
That time http://localhost:8000/ says  - Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by willydouhard** [comment]
Are you on windows? If so can you try to uncomment and set `# follow_symlink = true` in your `.chainlit/.config.toml` file?

**Comment by bhushan-ss** [comment]
Yes I am on windows. I have uncommented and changed follow_symlink = true but still same issue.

**Comment by willydouhard** [comment]
This [discord post](https://discord.com/channels/1088038867602526210/1155944774700892250/1156056692258259064) looks similar

**Comment by bhushan-ss** [comment]
I don't have access to above discord post

**Comment by willydouhard** [comment]
Here is a screenshot
<img width="517" alt="Screenshot 2023-09-27 at 21 55 53" src="https://github.com/Chainlit/docs/assets/13104895/35e25dbf-1f1a-4451-8da7-eb11cd80d058">

**Comment by bhushan-ss** [comment]
Above issue is solved but now I am getting below error;
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open vectorstore\db_faiss\index.faiss for reading: No such file or directory

**Comment by willydouhard** [comment]
Would need to see the code to help but this is not a Chainlit error. Found those issue that might help:
- https://github.com/facebookresearch/faiss/issues/3004
-https://github.com/langchain-ai/langchain/issues/5725
