### ISSUE TITLE
How to collect data from human feedback

### ISSUE THREAD

**Issue by kiangkiangkiang** [Chainlit/docs#74]
I'm trying to collect the data from human feedback (negative feedback & positive feedback & additional feedback).

But I couldn't find any callback function that the "Submit feedback" button invoke. 

<img width="612" alt="截圖 2023-11-15 下午5 30 24" src="https://github.com/Chainlit/docs/assets/44896160/0c82e4d1-0ced-449d-9147-c0f45e58278c">

Is there any Python decorator that can catch the event or any way to solve the problem?

**Comment by willydouhard** [comment]
You cannot react to the human feedback atm, you can however retrieve the data at a later stage using the [python cloud client](https://docs.chainlit.io/api-reference/cloud-client/getting-started).
