### ISSUE TITLE
setting hide_cot to true still shows chain of thoughts

### ISSUE THREAD

**Issue by suman12345678** [Chainlit/docs#75]
Path: /observability-iteration/chain-of-thought

**Comment by willydouhard** [comment]
Can you provide a snippet of code to reproduce as well as a screenshot?

**Comment by suman12345678** [comment]
Hi Chainlit/docs

Thanks a lot for replying.

I have code spread in many module so I cannot share snippet. But here is
what I am doing.

Under .chainlit/config I am changing hide_cot to true and running my app. I
am using pandasai and azuregpt4 llm , I still see the chain of thoughts
printing when I am calling by chainlit run app.py from anaconda prompt.

I want to avoid this printing be cause if I deploy it in server logs will
be filled by chain of thoughts. So if you can help me to know if there are
any other settings I should do, that would be great.

Thanks
Suman

**Comment by willydouhard** [comment]
Can you share a screenshot (you can blur sensitive data)? Just to make sure we are talking about the same thing!

**Comment by suman12345678** [comment]
Hi Chainlit/docs,

Below are some part of code.
def get_response(message):
    question=message
    message = prompt+message

    chain = cl.user_session.get('credit model')
    response =  None

    # Retry the OpenAI API call if it fails
    for attempt in range(max_retries):
        try:
            response = chain.chat(message)


@cl.on_chat_start
async def on_chat_start():

    llm=define_llm()
    app_user = cl.user_session.get("user")
    await cl.Avatar(
        name = "Chatbot1",
        path="chatbot.PNG"
    ).send()
    await cl.Message(content=f"Hi! {app_user.username} I'm an assistant. \
                     How can I assist you?",\
                     author="Chatbot1").send()

    credit = SmartDataframe(df,config={"llm": llm,"save_logs":False, \

"conversational": True, \

"enable_cache":False,

"verbose":False})



    # creating user session to store data
    cl.user_session.set('credit model',credit)

get_response_async = make_async(get_response)

@cl.on_message  # called when user provide a input
async def main(message: str):
    print('user message ',message)


    # making long running script as async
    response=await  get_response_async(message)

    print('---------return ',response)
    # Send a response back to the user
    await cl.Message(
        content=str(response),author="Chatbot1"
    ).send()





Thanks and Regards
Suman Mukhopadhyay
+1 973-309-2196

**Comment by suman12345678** [comment]
Hi Teamc
Could you please remove my contacts information from the issue description?

**Comment by suman12345678** [comment]
Please delete personal information or contact from the comments.

**Comment by suman12345678** [comment]
Hi Team

Ignore it. I could do it myself
