### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by supritshah1289** [Chainlit/docs#76]
Path: /examples/qa

Chainlit version 0.6.2 
https://docs.chainlit.io/examples/qa

Error on UI screen: Message.init() got an unexpected keyword argument 'disable_human_feedback'

 \site-packages\chainlit\utils.py", line 36, in wrapper
    return await user_function(**params_values)

**Comment by willydouhard** [comment]
Yes this parameter is introduced later. Can you run `pip install -U chainlit`?

**Comment by supritshah1289** [comment]
@willydouhard ran the command and still getting the same error

**Comment by willydouhard** [comment]
@supritshah1289 Everything is working on my end. Are you sure you upgraded Chainlit? Maybe you have multiple versions of Python installed and you are not using the correct one when starting the Chainlit app?

**Comment by ModEnter** [comment]
The code snippet provided on https://docs.chainlit.io/examples/qa uses features introduced after version 0.6.2
