### ISSUE TITLE
Elements: Not showing as docs describe it

### ISSUE THREAD

**Issue by bachi76** [Chainlit/docs#82]
I couldn't make the text (and image) elements to display as is described in the docs on [/api-reference/elements/text](https://docs.chainlit.io/api-reference/elements/text)

The only way that seems to work is with message context and display = "inline". All the other described versions (outside of message context, and other display types, didn't show the elements at all. What am I doing wrong? Or is the doc outdated?

Being able to display text or image permanently, out of a message context, would be extremely helpful.

Thanks.

**Comment by willydouhard** [comment]
To display an element permanently, `display="inline"` is the right way. If you want do use `display="side"`, the name of the element has to be referenced in the content of the message. That name will become an hyperlink opening the sidebar.

**Comment by willydouhard** [comment]
Yes, remove and send is the way. For the auto open in the side bar this will come!
