### ISSUE TITLE
"Prompt Playground error: No LLM provider available"

### ISSUE THREAD

**Issue by wangpengfei2048** [Chainlit/docs#84]
I get the following error when clicking on the "Inspect in prompt playground" icon.
"Prompt Playground error: No LLM provider available"

If I set the .env file(include the OPENAI_API_KEY and OPENAI_API_BASE),   there is no this problem.

but I what to set it with the config ? how the set the env? Is there some example?

**Comment by willydouhard** [comment]
To use the prompt playground you have to at least enable one LLM provider. LLM providers are enabled through specific environment variables such as `OPENAI_API_KEY`.

The easiest way to define it is to create a `.env` file at the same level as your app file such as:

```bash .env
OPENAI_API_KEY="sk..."
```

**Comment by wangpengfei2048** [comment]
If use the .env file , it is OK.  
     I use other way,  it is OK, too.  I set the uesr_env in the file 'chainlit-config.toml':
uesr_env=["OPENAI_API_KEY"]
     But I dont know why? I dont set the environment variables for OPENAI_API_KEY

**Comment by willydouhard** [comment]
That is weird. Either way you should not put secrets in the chainlit config as you might commit it to your repo.

**Comment by wangpengfei2048** [comment]
All user use the same key,   I set the key in the .env file

**Comment by ModEnter** [comment]
Hello, since the prompt playground has been removed from Chainlit, I'm closing the issue
