### ISSUE TITLE
sample code for react custom frontend with document attachment facility

### ISSUE THREAD

**Issue by suman12345678** [Chainlit/docs#89]
Hi Team,

are there any sample code for chainlit and react together to handle document attachment from custom react frontend screen and chainlit as backend. The example works fine when chainlit as frontend, but if I want to have custom react frontend and chainlit as backend, are there any sample code for react code?. Thanks in advance

**Comment by ModEnter** [comment]
Hello, to make a custom frontend, you can re-use the chainlit react frontend example, and change whatever you need to make it correspond your needs. I'm closing the issue
