### ISSUE TITLE
Render deployment link broken

### ISSUE THREAD

**Issue by jalakoo** [Chainlit/docs#91]
Path: /get-started/deployment

Instead of linking to a guide or template for setting up a Chainlit deployment with render.com, link goes to the Discord invite.

**Comment by willydouhard** [comment]
Right now the render guide is a discord thread, so you first have to join the discord to read it. Will make a better one in the future!

**Comment by jalakoo** [comment]
Ok. Posting link to that Discord thread for anyone else:  https://discord.com/channels/1088038867602526210/1126834266504966294/1126845898287230977
