### ISSUE TITLE
Chainlit deployment for multiple worker in production

### ISSUE THREAD

**Issue by suman12345678** [Chainlit/docs#96]
Hi Team,

Thanks a lot for the wonderful work. I know more documentation will be available in future, but here is some questions I have if you can help me.

Are there any ways to use multiple worker while deploying in production? 
Are there any default setting of number of worker when we run 'chainlit run myapp.py'
Where does the session stored? (In case I want to run with multiple workers, can I assume that for a particular session it can always find its session variable ? in cloud the assigned worker for a request can be changed for a single session unless session affinity is in place)

**Comment by ModEnter** [comment]
Chainlit does not provide fast way to easily add instances, since this issue is out of the project scope. If you want to parallelise processes, you can use a load balancer with multiple instances.
