### ISSUE TITLE
Issue on docs - You need to configure at least an on_chat_start or an on_message callback

### ISSUE THREAD

**Issue by ThrivingHenry** [Chainlit/docs#97]
Path: /integrations/langchain

I installed langchain + chainlit, set my .env with my openAI key, and copied the async LCEL code identically to my app.py.

When I run "chainlit run app.py -w" it shows:
![image](https://github.com/Chainlit/docs/assets/134826764/21f41334-9623-4464-86d7-22ddbce0fa05)

In terminal, it shows: `You need to configure at least an on_chat_start or an on_message callback` but it's clearly defined in the default code.

Any sense what I could have done wrong here?

**Comment by willydouhard** [comment]
What version of chainlit are you using? Also does it work if you remove -w?

**Comment by ModEnter** [comment]
This issue has been fixed in more recent versions. I'm closing the issue. The code snippet for async LCEL langchain/openAI integration gives the following window :
<img width="1443" alt="image" src="https://github.com/user-attachments/assets/bc443f66-15ca-4dea-a7b5-543da14c653d">
